In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
    print(e)

1
2
3


In [5]:
for e in A:
    print(e)

1
2
3


In [6]:
L.append(4)

In [7]:
L

[1, 2, 3, 4]

In [8]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [9]:
L = L + [5]

In [10]:
L

[1, 2, 3, 4, 5]

In [11]:
A = A + [4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [12]:
L2 = []
for e in L:
    L2.append(e+e)
L2

[2, 4, 6, 8, 10]

In [13]:
A+A

array([2, 4, 6])

In [14]:
2*A

array([2, 4, 6])

In [15]:
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [16]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [17]:
A**2

array([1, 4, 9])

In [18]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [19]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [20]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])