In [1]:
import numpy as np

In [2]:
M = np.array([[1,2], [3,4]])

In [3]:
L = [[1,2], [3,4]]

In [4]:
L[0][0]

1

In [5]:
M[0][0]

1

In [6]:
M[0,0]

1

In [7]:
M.T

array([[1, 3],
       [2, 4]])

In [8]:
Z = np.zeros(10)

In [9]:
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
x = np.random.random((10,10))

In [15]:
x

array([[0.01253406, 0.15216769, 0.70726641, 0.56222318, 0.98958916,
        0.47665767, 0.61948881, 0.81045923, 0.45427733, 0.6256985 ],
       [0.16330635, 0.95202456, 0.41512816, 0.01861133, 0.04552839,
        0.142357  , 0.3416423 , 0.05638248, 0.33539693, 0.45700968],
       [0.42416837, 0.23916608, 0.48499872, 0.77768933, 0.06385241,
        0.34081877, 0.64046949, 0.46230927, 0.44704344, 0.79771562],
       [0.38494718, 0.18408469, 0.02773224, 0.50308092, 0.73022249,
        0.16867465, 0.9166076 , 0.54358628, 0.94008779, 0.73418766],
       [0.17090145, 0.22743922, 0.10418522, 0.79554955, 0.40123974,
        0.6649016 , 0.69801022, 0.96980088, 0.99818161, 0.16058572],
       [0.78598695, 0.81487338, 0.11787701, 0.73481582, 0.30043513,
        0.40882628, 0.24404148, 0.5711521 , 0.99671529, 0.58413917],
       [0.6966722 , 0.97020944, 0.04292917, 0.536552  , 0.78177585,
        0.35703162, 0.14446983, 0.78280395, 0.87650754, 0.87166185],
       [0.18489733, 0.43106137, 0.3032973

In [18]:
G = np.random.randn(10,10)

In [19]:
G.mean()

-0.02791576626279917

In [20]:
G.var()

1.0931969615782489